FROM node:24-alpine AS build
WORKDIR /app


COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine AS deploy
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]